### ISSUE TITLE
vevo youtube not working

### ISSUE THREAD

**Issue by jakop345** [danog/video-dl#753]
Youtube's vevo videos are not working though they are working on youtube-dl.

**Comment by danog** [comment]
I tested with http://video.daniil.it/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-j99S1dn1wE and it seems to work.

**Comment by jakop345** [comment]
Ya i am getting the download, but its size is 0 bytes.May be an ip issue.

**Comment by danog** [comment]
@jakop345 Yeah, that's probably the problem.

**Comment by jakop345** [comment]
I think youtube-dl  should be updated.

**Comment by danog** [comment]
@jakop345 youtube-dl is up-to-date (2016.06.26)
