### ISSUE TITLE
Can we deploy the api on heroku

### ISSUE THREAD

**Issue by jakop345** [danog/video-dl#754]
Can i deploy the api server on heroku ?If so help me.

**Comment by danog** [comment]
It should be easy as cloning the repo somewhere on heroku and pointing the webroot to the api folder.
You have to install mediainfo, wget, curl, awk, sed and youtube-dl first though.
I suggest you run the api.sh script manually the first time to check if there are any more missing dependencies you have to install.
Let me know if it worked!

**Comment by jakop345** [comment]
Ya it is working but i used youtube-dl-api-server as my api server.
